### ISSUE TITLE
Login to cluster fails

### ISSUE THREAD

**Issue by jbeckers** [redhat-developer/intellij-openshift-connector#102]
[kind/bug]

## What versions of software are you using?
- Operating System: Windows 10 1903
- IntelliJ version: 2019.3 EAP8
- OpenShift version: 

## What did you run exactly?
Try to login to cluster

## Actual behavior
Nothing happens

## Expected behavior
I'm logged in to the cluster

## Any logs, error output, etc?
IDEA Fatal errors shows
```
java.lang.ClassCastException: class com.intellij.openapi.actionSystem.impl.ActionMenu cannot be cast to class com.intellij.ui.treeStructure.Tree (com.intellij.openapi.actionSystem.impl.ActionMenu and com.intellij.ui.treeStructure.Tree are in unnamed module of loader com.intellij.util.lang.UrlClassLoader @3bfdc050)
	at org.jboss.tools.intellij.openshift.actions.TreeAction.getTree(TreeAction.java:32)
	at org.jboss.tools.intellij.openshift.actions.TreeAction.update(TreeAction.java:38)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:177)
	at com.intellij.ide.util.gotoByName.GotoActionModel.updateActionBeforeShow(GotoActionModel.java:303)
	at com.intellij.ide.util.gotoByName.GotoActionModel$ActionWrapper.lambda$getPresentation$0(GotoActionModel.java:652)
	at com.intellij.ide.util.gotoByName.GotoActionModel.lambda$updateOnEdt$4(GotoActionModel.java:456)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:309)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:441)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:906)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:779)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:421)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by adietish** [comment]
Hi @jbeckers
thanks for reporting. What's the version of your OpenShift cluster?

**Comment by jbeckers** [comment]
odo v1.0.0 (4e3175e6f)

Server: https://[SNIPSNIPSNIP]
OpenShift: v3.10.34
Kubernetes: v1.10.0+b81c8f8

**Comment by jbeckers** [comment]
Some more info:

Since the last update of the plugin, it now remembers the cluster url. Before, the plugin would always revert to the default url (at least in the tool window)

When I've freshly started IDEA, the tool window says "please log in to cluster".
When I click "about" in the context menu of the cluster line in the tool window, I just get a terminal tool window with "odo v1.0.0 (4e3175e6f)" in it
Upon checking the cluster login details, it has not remembered the username and password.

When I re-enter my username and password, and click "about" again, I get:
"odo v1.0.0 (4e3175e6f)
Server: https://[SNIPSNIPSNIP]
OpenShift: v3.10.34
Kubernetes: v1.10.0+b81c8f8"

Still, the tool window shows "please login to cluster"

**Comment by adietish** [comment]
@jbeckers The plugin is still in early stages in terms of comfort, but it'll improve now that the team grew. 
About your error, I am now not sure if your login fails or if the error simply is that you're still told to log in even though you are? Is there any additional output, logs, dialogs that would unveil more details?
What means do you use to log in: username & password / token? If you use those with oc or odo in the cmd line, does it work?

**Comment by jeffmaury** [comment]
That maybe a side effect of your account on the cluster having no projects at all. Can you try to create a project from the cluster node context menu ?

**Comment by adietish** [comment]
@jeffmaury @jbeckers I just could reproduce it, but I dont know yet when this happens exactly. Investigating.

**Comment by adietish** [comment]
@jbeckers I'm on a fix. My current situation where I can reproduce your problem is caused by an expired token. Login with a new token successfully performed by odo but intellij is not updated.
I'd love to see if this also the case for you: after logging in with a valid/new token, are you authenticated  aka bale to perform operations in cli with odo (ex. list components)?

**Comment by jbeckers** [comment]
I'm using password login, not token.

I'm not even getting to where I can use odo. This is what my terminal looks like today after again entering username/password:

```
odo v1.0.0 (4e3175e6f)

Server: https://osclu-azu01-mgmt-api.uz.kuleuven.ac.be:8443
OpenShift: v3.10.34
Kubernetes: v1.10.0+b81c8f8

---
A newer version of odo (v1.0.1) is available,
visit https://github.com/openshift/odo/releases to update.
If you wish to disable this notification, run:
odo preference set UpdateNotification false
---
```
but there's no prompt.

Could it be that I don't have the right access rights on the cluster to connect using odo?

**Comment by jbeckers** [comment]
Same result when using token login.

**Comment by adietish** [comment]
@jbeckers by terminal I mean your system command prompt, powershell or whatever you use outside of intellij. Our plugin is using the odo binary which is thus present and usable independently of intellij  (either you downloaded it and put it on your %PATH% or we downloaded it for you and stored it in <USER HOME>\.odo\cache\<VERSION>/odo). 
My current understanding is that the login that you execute actually works but IntelliJ is failing to refresh it's UI and reflect it. To verify that it would be awesome if you could try to use odo on your system shell (cli, command prompt, power shell, ...) and see if you're logged in there. Makes sense?

**Comment by jbeckers** [comment]
For future reference, if anyone ever comes across this: issue is definitely not fixed, I just gave up on it
