### ISSUE TITLE
Enable 'Describe' command for 'not pushed' components

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/intellij-openshift-connector#176]
[kind/Enhancement]

## Which functionality do you think we should update/improve?

See https://github.com/redhat-developer/vscode-openshift-tools/issues/1464
https://issues.redhat.com/browse/JBIDE-27122

**Comment by mohitsuman** [comment]
Fixed with the latest odo release. @sbouchet can you please confirm ?

**Comment by sbouchet** [comment]
odo (2.4.2) currently fails with 
```
 ⚠  URLs couldn't not be retrieved: unable to list routes: the component name, the app name or both are empty
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x88 pc=0x263c7a5]

goroutine 1 [running]:
github.com/openshift/odo/pkg/envinfo.(*EnvInfo).ListStorage(0xc0009244b0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/envinfo/storage.go:149 +0xa5
github.com/openshift/odo/pkg/component.(*ComponentFullDescription).loadStoragesFromClientAndLocalConfig(0xc000245080, 0xc00061a000, 0x3603638, 0xc000924480, 0x7ffd7f9d5f5e, 0x7, 0x7ffd7f9d5f5a, 0x3, 0xc0006a8240, 0x0, ...)
        /builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/component/component_full_description.go:73 +0x103
github.com/openshift/odo/pkg/component.NewComponentFullDescriptionFromClientAndLocalConfigProvider(0xc00061a000, 0xc000924480, 0x7ffd7f9d5f5e, 0x7, 0x7ffd7f9d5f5a, 0x3, 0x7ffd7f9d5f3f, 0x14, 0xc0007309b0, 0xe, ...)
        /builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/component/component_full_description.go:199 +0x905
github.com/openshift/odo/pkg/odo/cli/component.(*DescribeOptions).Run(0xc00044c4e0, 0xc0007fe000, 0x0, 0x0)
        /builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/describe.go:68 +0x9b
github.com/openshift/odo/pkg/odo/genericclioptions.GenericRun(0x35c0410, 0xc00044c4e0, 0xc0007fe000, 0xc00061ceb0, 0x1, 0x5)
        /builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/genericclioptions/runnable.go:97 +0x479
github.com/openshift/odo/pkg/odo/cli/component.NewCmdDescribe.func1(0xc0007fe000, 0xc00061ceb0, 0x1, 0x5)
        /builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/describe.go:96 +0x5e
github.com/spf13/cobra.(*Command).execute(0xc0007fe000, 0xc00061ce60, 0x5, 0x5, 0xc0007fe000, 0xc00061ce60)
        /builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:856 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc00089d400, 0xc000120000, 0x2ec1ec0, 0x49a2488)
        /builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:897
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:890
main.main()

```

**Comment by sbouchet** [comment]
opened https://github.com/openshift/odo/issues/5245

**Comment by sbouchet** [comment]
closed as fixed with #507
