### ISSUE TITLE
Can't see any clusters

### ISSUE THREAD

**Issue by rkreienbuehl** [redhat-developer/intellij-openshift-connector#182]
[kind/bug]

## What versions of software are you using?
- Operating System: macOS 10.15.4
- IntelliJ version: 2019.3.4
- OpenShift version: Cluster: 3.11 / Plugin: 0.2.0.96

## What did you run exactly?
I have installed the actual version of the Openshift Connector. Via terminal I have used a Openshift Cluster in the internet and my local Minishift cluster.

## Actual behavior
The plugin window is an empty list, without any content.
![Bildschirmfoto 2020-03-30 um 07 36 13](https://user-images.githubusercontent.com/19514737/77878682-28c6e280-7259-11ea-83a8-c78e20305aa4.png)

## Expected behavior
As I had in previous versions of IntelliJ I expect to see m clusters I have already used.

## Any logs, error output, etc?
```
2020-03-30 07:13:00,198 [   9529]  ERROR - .wm.impl.ToolWindowManagerImpl - failed to init toolwindow org.jboss.tools.intellij.openshift.WindowToolFactory 
	at org.jboss.tools.intellij.openshift.tree.application.ApplicationTreeModel.addContext(ApplicationTreeModel.java:132)
	at org.jboss.tools.intellij.openshift.tree.application.ApplicationTreeModel.loadProjectModel(ApplicationTreeModel.java:109)
	at org.jboss.tools.intellij.openshift.tree.application.ApplicationTreeModel.<init>(ApplicationTreeModel.java:90)
	at org.jboss.tools.intellij.openshift.WindowToolFactory.createToolWindowContent(WindowToolFactory.java:43)
2020-03-30 07:13:00,202 [   9533]  ERROR - .wm.impl.ToolWindowManagerImpl - Plugin to blame: OpenShift Connector by Red Hat version: 0.2.0.96 
```

**Comment by jeffmaury** [comment]
Duplicates of #173
