### ISSUE TITLE
NodeJS Component creation ends up with Failed to load application deployments configs

### ISSUE THREAD

**Issue by odockal** [redhat-developer/intellij-openshift-connector#461]
[kind/bug]

## What versions of software are you using?
- Operating System: Fedora 36
- IntelliJ version: 2022.2.3
- OpenShift version: 0.12.0.139

## What did you run exactly?
1. Connect to the cluster
2. Create empty project in workspace
3. Create project on cluster
4. New component -> Node JS runtime - nodejs starter

## Actual behavior
Component is not created, instead there is tree item with text above and there is an error in intellij log

## Expected behavior
Component is created and there is no error

## Any logs, error output, etc?
```
java.io.IOException: Process exited with an error: 1 (Exit value: 1) {
	"message": "No valid devfile found for project in /home/odockal/IdeaProjects/nodejs"
}

	at com.redhat.devtools.intellij.common.utils.ExecHelper.executeWithResult(ExecHelper.java:261)
	at org.jboss.tools.intellij.openshift.utils.odo.OdoCli.execute(OdoCli.java:221)
	at org.jboss.tools.intellij.openshift.utils.odo.OdoCli.analyze(OdoCli.java:319)
	at org.jboss.tools.intellij.openshift.utils.odo.OdoProjectDecorator.analyze(OdoProjectDecorator.java:78)
	at org.jboss.tools.intellij.openshift.ui.component.CreateComponentModel.setContext(CreateComponentModel.java:106)
	at org.jboss.tools.intellij.openshift.ui.component.CreateComponentDialogStep$2.textChanged(CreateComponentDialogStep.java:72)
	at com.intellij.ui.DocumentAdapter.insertUpdate(DocumentAdapter.java:15)
	at java.desktop/javax.swing.text.AbstractDocument.fireInsertUpdate(AbstractDocument.java:226)
	at java.desktop/javax.swing.text.AbstractDocument.handleInsertString(AbstractDocument.java:780)
	at java.desktop/javax.swing.text.AbstractDocument.insertString(AbstractDocument.java:739)
	at java.desktop/javax.swing.text.PlainDocument.insertString(PlainDocument.java:131)
	at java.desktop/javax.swing.text.AbstractDocument.replace(AbstractDocument.java:698)
	at java.desktop/javax.swing.text.JTextComponent.setText(JTextComponent.java:1729)
	at org.jboss.tools.intellij.openshift.ui.component.CreateComponentDialogStep.loadModel(CreateComponentDialogStep.java:168)
	at org.jboss.tools.intellij.openshift.ui.component.CreateComponentDialogStep.prepare(CreateComponentDialogStep.java:191)
	at com.intellij.ui.wizard.WizardModel.prepareCurrentStep(WizardModel.java:175)
	at com.intellij.ui.wizard.WizardModel.getCurrentStep(WizardModel.java:124)
	at com.intellij.ui.wizard.WizardDialog.initCurrentStep(WizardDialog.java:159)
	at com.intellij.ui.wizard.WizardDialog.init(WizardDialog.java:119)
	at com.intellij.ui.wizard.WizardDialog.<init>(WizardDialog.java:41)
	at org.jboss.tools.intellij.openshift.ui.component.CreateComponentDialog.<init>(CreateComponentDialog.java:18)
	at org.jboss.tools.intellij.openshift.actions.component.CreateComponentAction.showDialog(CreateComponentAction.java:105)
	at org.jboss.tools.intellij.openshift.actions.component.CreateComponentAction.lambda$process$3(CreateComponentAction.java:83)
	at com.redhat.devtools.intellij.common.utils.UIHelper.lambda$executeInUI$0(UIHelper.java:34)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:513)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:95)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:75)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:118)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:918)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:766)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:449)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:624)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:447)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at com.redhat.devtools.intellij.common.utils.ExecHelper.executeWithResult(ExecHelper.java:258)
	... 55 more
```

**Comment by odockal** [comment]
This issue seems to be connected to empty project content (or its misalignment during project creation) on my side (or intellij). When project is properly created (contains .idea and *.iml files) this seems to work.
