### ISSUE TITLE
Bug - exception on startup - failed to fetch api groups from kubernetes: Unauthorized"

### ISSUE THREAD

**Issue by sreich** [redhat-developer/intellij-openshift-connector#519]
[kind/bug]

## What versions of software are you using?
- Operating System:Windows
- IntelliJ version:
- OpenShift version:1.2.0.168

## What did you run exactly?
I started Intellij. I previously had connected it to the cluster and added components, it seems that it's giving issues with it now. Doesn't seem to gracefully handle these connection changes

## Any logs, error output, etc?
java.io.IOException: Process exited with an error: 1 (Exit value: 1) {
	"message": "unable to list all dynamic resources required to find components: failed to fetch api groups from kubernetes: Unauthorized"
}

	at com.redhat.devtools.intellij.common.utils.ExecHelper.executeWithResult(ExecHelper.java:261)
	at org.jboss.tools.intellij.openshift.utils.odo.OdoCli.execute(OdoCli.java:244)
	at org.jboss.tools.intellij.openshift.utils.odo.OdoCli.discover(OdoCli.java:856)
	at org.jboss.tools.intellij.openshift.utils.odo.OdoProjectDecorator.discover(OdoProjectDecorator.java:263)
	at org.jboss.tools.intellij.openshift.tree.application.ApplicationsRootNode.addContext(ApplicationsRootNode.java:138)
	at org.jboss.tools.intellij.openshift.tree.application.ApplicationsRootNode.loadProjectModel(ApplicationsRootNode.java:109)
	at org.jboss.tools.intellij.openshift.tree.application.ApplicationsRootNode.lambda$initializeOdo$0(ApplicationsRootNode.java:83)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:887)
	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2325)
	at org.jboss.tools.intellij.openshift.tree.application.ApplicationsRootNode.initializeOdo(ApplicationsRootNode.java:78)
	at org.jboss.tools.intellij.openshift.tree.application.ApplicationsTreeStructure.getApplicationsRoot(ApplicationsTreeStructure.java:87)
	at org.jboss.tools.intellij.openshift.tree.application.ApplicationsTreeStructure.getChildElements(ApplicationsTreeStructure.java:99)
	at com.intellij.ui.tree.StructureTreeModel.getValidChildren(StructureTreeModel.java:412)
	at com.intellij.ui.tree.StructureTreeModel.validateChildren(StructureTreeModel.java:330)
	at com.intellij.ui.tree.StructureTreeModel.getNode(StructureTreeModel.java:324)
	at com.intellij.ui.tree.StructureTreeModel.getChildren(StructureTreeModel.java:344)
	at com.intellij.ui.tree.AsyncTreeModel$CmdGetChildren.getNode(AsyncTreeModel.java:548)
	at com.intellij.ui.tree.AsyncTreeModel$Command.get(AsyncTreeModel.java:443)
	at com.intellij.ui.tree.AsyncTreeModel$Command.get(AsyncTreeModel.java:409)
	at com.intellij.util.concurrency.Invoker$Task.run(Invoker.java:305)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1111)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:71)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:128)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:109)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:68)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:68)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:106)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:71)
	at com.intellij.util.concurrency.Invoker.invokeSafely(Invoker.java:187)
	at com.intellij.util.concurrency.Invoker.lambda$offerSafely$0(Invoker.java:165)
	at com.intellij.util.concurrency.Invoker$Background.lambda$offer$0(Invoker.java:475)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:243)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:29)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:216)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:212)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:205)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at com.redhat.devtools.intellij.common.utils.ExecHelper.executeWithResult(ExecHelper.java:258)
	... 51 more

**Comment by pdjames** [comment]
I am having the same issue, with the same exception stack

**Comment by sbouchet** [comment]
Hi,
Can you try to log in again to the cluster ? Is it a kubernetes or an openshift cluster ?

**Comment by sreich** [comment]
It's an openshift cluster, I was able to log into it but of course eventually the tokens expire. Unsure what other info I could provide. I do have podman installed/setup in intellij, but I assume this plugin does not look at that and would not get confused by its existence

**Comment by sreich** [comment]
Thanks!
