### ISSUE TITLE
java.lang.NullPointerException Odo.getMasterUrl()

### ISSUE THREAD

**Issue by rsearls** [redhat-developer/intellij-openshift-connector#536]
ENV: 
    Fedora 35

    Intellij IDEA 222.1 (Community Edition) bld #IC-222.3739.54
    Runtime version: 17.0.3+7-b469.37 amd64
    VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

odo is in my classpath.  Verified by
  1668 > which odo
  ~/bin/odo

Exception in plugin OpenShift Toolkit by Red Hat (1.2.0.168)
java.lang.NullPointerException: Cannot invoke "org.jboss.tools.intellij.openshift.utils.odo.Odo.getMasterUrl()" because "this.delegate" is null
	at org.jboss.tools.intellij.openshift.utils.odo.OdoProjectDecorator.getMasterUrl(OdoProjectDecorator.java:258)
	at org.jboss.tools.intellij.openshift.tree.application.ApplicationsTreeStructure.lambda$createDescriptor$14(ApplicationsTreeStructure.java:246)
	at com.redhat.devtools.intellij.common.tree.LabelAndIconDescriptor.processLabel(LabelAndIconDescriptor.java:74)
	at com.redhat.devtools.intellij.common.tree.LabelAndIconDescriptor.update(LabelAndIconDescriptor.java:64)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.getUpdatedPresentation(PresentableNodeDescriptor.java:78)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.update(PresentableNodeDescriptor.java:30)
	at com.intellij.ui.tree.StructureTreeModel$Node.update(StructureTreeModel.java:458)
        ...

**Comment by adietish** [comment]
To me it's far from obvious how this could even happen. The `delegate` that's causing the NPE is initialized as with the instance that is creating it:
[ApplicationRootNode#initializeOdo](https://github.com/redhat-developer/intellij-openshift-connector/blob/main/src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationsRootNode.java#L82)
```java
public CompletableFuture<Odo> initializeOdo() {
        return OdoCliFactory.getInstance().getOdo(project).whenComplete((odo, err) -> {
            if (this.odo != null) {
                this.odo.release();
            }
            this.odo = new OdoProjectDecorator(odo, this);
            loadProjectModel(project);
        });
    }
```

@sbouchet: thoughts?

**Comment by mohitsuman** [comment]
@rsearls We made a new release of the plugin 1.6.0, can you please re-verify if this issue still persists for you.

**Comment by adietish** [comment]
I cannot replicate this. Closing as CANNOT_REPLICATE

**Comment by adietish** [comment]
Just found a way to reproduce this: remove/corrupt the file `<plugin-root>/src/main/resources/tools.json`. You'll see the NPE.
Reopening the issue.
