### ISSUE TITLE
Can't show log, nor refresh; java.lang.NoSuchMethodError at com.redhat.devtools.intellij.telemetry.core.service.TelemetryMessageBuilder$Message

### ISSUE THREAD

**Issue by fizdiq** [redhat-developer/intellij-openshift-connector#651]
[kind/bug]

## What versions of software are you using?
- Operating System: Windows 11 Enterprise
- IntelliJ version: IntelliJ IDEA 2023.3.2 (Ultimate Edition)
- OpenShift version: Openshift 4.x

## What did you run exactly?
Trying to open the logs from a pod 

## Actual behavior
Error occurred, with logs shown below.

## Expected behavior
Opened the Kubernetes Console tab and then showing the logs of the pod

## Any logs, error output, etc?

```
java.lang.NoSuchMethodError: 'com.redhat.devtools.intellij.telemetry.core.service.TelemetryMessageBuilder$Message com.redhat.devtools.intellij.telemetry.core.service.TelemetryMessageBuilder$ActionMessage.property(java.lang.String, java.lang.String)'
	at com.redhat.devtools.intellij.kubernetes.telemetry.TelemetryService.sendTelemetry(TelemetryService.kt:44)
	at com.redhat.devtools.intellij.kubernetes.actions.RefreshAction.actionPerformed$lambda$0(RefreshAction.kt:31)
	at com.redhat.devtools.intellij.kubernetes.actions.ExtensionsKt$run$1.run(Extensions.kt:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:434)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:132)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:484)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:248)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:248)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:498)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:81)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:81)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:86)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:81)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:464)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by adietish** [comment]
This is caused by binary incompatible Telemetry 1.1.0 breaking consuming plugins. We're releasing a new version of the openshift plugin to fix this.
In the meantime you can fix this by downgrading the telemetry plugin to 1.0.0. See https://github.com/redhat-developer/intellij-quarkus/issues/1301#issuecomment-1870161138

**Comment by adietish** [comment]
@fizdiq new build v1.2.3 was submitted to marketplace awaiting approval. It should become available within 48h
