### ISSUE TITLE
IntegrationTests are failing for `OdoCliServiceTest.testCheckCreateService`

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-openshift-connector#827]
```java
org.jboss.tools.intellij.openshift.utils.odo.OdoCliServiceTest

  Test testCheckCreateService FAILED (15.8s)

  junit.framework.AssertionFailedError
      at junit.framework.Assert.fail(Assert.java:55)
      at junit.framework.Assert.assertTrue(Assert.java:22)
      at junit.framework.Assert.assertNotNull(Assert.java:256)
      at junit.framework.Assert.assertNotNull(Assert.java:248)
      at junit.framework.TestCase.assertNotNull(TestCase.java:391)
      at org.jboss.tools.intellij.openshift.utils.odo.OdoCliTest.getServiceTemplate(OdoCliTest.java:125)
      at org.jboss.tools.intellij.openshift.utils.odo.OdoCliServiceTest.createService(OdoCliServiceTest.java:51)
      at org.jboss.tools.intellij.openshift.utils.odo.OdoCliServiceTest.testCheckCreateService(OdoCliServiceTest.java:23)
      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.base/java.lang.reflect.Method.invoke(Method.java:568)
      at junit.framework.TestCase.runTest(TestCase.java:177)
      at com.intellij.testFramework.UsefulTestCase.lambda$runBare$11(UsefulTestCase.java:483)
      at com.intellij.testFramework.UsefulTestCase.lambda$wrapTestRunnable$13(UsefulTestCase.java:504)
      at com.intellij.testFramework.UsefulTestCase.runTestRunnable(UsefulTestCase.java:408)
      at com.intellij.testFramework.fixtures.BasePlatformTestCase.runTestRunnable(BasePlatformTestCase.java:109)
      at com.intellij.testFramework.UsefulTestCase.defaultRunBare(UsefulTestCase.java:424)
      at com.intellij.testFramework.UsefulTestCase.lambda$runBare$12(UsefulTestCase.java:491)
      at com.intellij.testFramework.EdtTestUtil.lambda$runInEdtAndWait$5(EdtTestUtil.java:91)
      at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
      at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
      at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
      at com.intellij.openapi.application.impl.RwLockHolder.runIntendedWriteActionOnCurrentThread(RwLockHolder.kt:204)
      at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:830)
      at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:419)
      at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:101)
    	at com.intellij.openapi.application.impl.RwLockHolder.runWithoutImplicitRead(RwLockHolder.kt:105) 
    	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:593) 
    	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:77) 
    	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:362) 
    	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:361) 
    	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:843) 
    	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:361) 
    	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:356) 
    	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1021) 
    	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:114) 
    	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1021) 
    	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:356) 
    	at com.intellij.openapi.application.impl.RwLockHolder.runIntendedWriteActionOnCurrentThread(RwLockHolder.kt:209) 
    	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:830) 
    	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:398) 
    	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207) 
    	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128) 
    	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117) 
    	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113) 
    	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105) 
    	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92) 
     


org.jboss.tools.intellij.openshift.utils.odo.OdoCliServiceTest > testCheckCreateService FAILED
    junit.framework.AssertionFailedError
        at junit.framework.Assert.fail(Assert.java:55)
        at junit.framework.Assert.assertTrue(Assert.java:22)
        at junit.framework.Assert.assertNotNull(Assert.java:256)
        at junit.framework.Assert.assertNotNull(Assert.java:248)
        at junit.framework.TestCase.assertNotNull(TestCase.java:391)
        at org.jboss.tools.intellij.openshift.utils.odo.OdoCliTest.getServiceTemplate(OdoCliTest.java:125)
        at org.jboss.tools.intellij.openshift.utils.odo.OdoCliServiceTest.createService(OdoCliServiceTest.java:51)
        at org.jboss.tools.intellij.openshift.utils.odo.OdoCliServiceTest.testCheckCreateService(OdoCliServiceTest.java:23)
```

**Comment by adietish** [comment]
I cannot replicate locally since ITs are failing locally on other issues.
